---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
          ports:
            - containerPort: 80
          volumeMounts:
              - name: nginx-index
                mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index
        configMap:
          name: index-html
...

  
